#!/bin/bash

#chkconfig:2345 20 90
#description:zookeeper
#processname:zookeeper
case $1 in
          start) 
              /opt/kafka_2.12-1.0.0/bin/kafka-server-start.sh -daemon /opt/kafka_2.12-1.0.0/config/server.properties
              ;;
          stop)
              /opt/kafka_2.12-1.0.0/bin/kafka-server-stop.sh
              ;;
          restart)
              /opt/kafka_2.12-1.0.0/bin/kafka-server-stop.sh
	      /opt/kafka_2.12-1.0.0/bin/kafka-server-start.sh -daemon /opt/kafka_2.12-1.0.0/config/server.properties
              ;;
          *)
              echo "require start|stop|restart"
              ;;
esac
